version: "3.9"
services:
  db:
    image:  "sqilite3:14.5alpine"
    restart: always
    container_name: postgressql-server
    hostname: postgressql-server
    ports:
    -"5432:5432"
    volumes: ./pgdata:var/var/lib/postgresql/data
    environment:
    -   POSTGRES_USER=dbuser
    -   POSTGRES_PASSWORD=iab3302022
    -   POSTGRES_DB=iab330nodered
  nodered:
    image: nodered/node-red
    container_name: iab330nodered
    hostname: iab330nodered
    ports: 
    - "1880:1880"
    volumes:
    - ./nodered:/data
  pgadmin:
    image: dgpage/pgadmin4
    restart: always
    environmnent: 
      PGADMIN_DEFAULT_EMAIL: dulcedeyanira.acevedo@connect.edu.au
      PGADMIN_DEFAULT_PASSWORD: iab330db
      PGADMIN_LISTEN_PORT: 80
    ports:
     - "8080:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin
    links:
     -"db:postgresql-server"
  volumes:
    pgdata:
    pgadmin-data:

